### ISSUE TITLE
sending the same extrude request twice results in no action.

### ISSUE THREAD

**Issue by veive** [nokemono42/MP-Select-Mini-Web#10] opened 2018-03-24 15:10 UTC
To re-create this issue: open your printer interface and pre-heat your extruder.

Extrude 10mm.
Extrude 10mm again.

the printer will only extrude once.

**Comment by nokemono42** [comment] 2018-03-26 00:59
Positioning need to be set to relative, `G91`. Since Alpha 0.9.1 this is done automatically. If you home an axis, which triggers absolute position, `G91` will be sent again. 

I am going to add something that when a print is started, or detected, to reset the positioning. I didn't encounter this before because my starting GCode has G90, absolute positioning, then my ending GCode only has G91, relative positioning. I'm sure many people have various starting and ending GCodes.

Look for Alpha 0.9.5 in the new couple of days.

**Comment by nokemono42** [comment] 2018-03-27 13:40
This should now be fixed v0.9.5. I am closing this issue as I was able to reproduce and correct the problem. if you still have issues I can reopen it. Thanks

**Closed by nokemono42** 2018-03-27 13:40 UTC
Labels: bug
